apiVersion: v1
kind: Service
metadata:
  name: admin-server-service
spec:
  selector:
    app: admin-server  
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8041
    nodePort: 31110
